name: task_manager
description: Flutter aplication task manager
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter_driver:
    sdk: flutter
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  provider: ^6.1.1
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_secure_storage: ^9.0.0


  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter


  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/images/logo.png
  uses-material-design: true

